#!/bin/bash

set -exuo pipefail

root=$PWD

golangci-lint -c $root/.golangci.yml run ./pkg/proto/...
golangci-lint -c $root/.golangci.yml run ./pkg/vulners/...
golangci-lint -c $root/.golangci.yml run ./cmd/cli/...
golangci-lint -c $root/.golangci.yml run ./cmd/server/...